config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :garden_form, only: [:update], as: :garden_form do
    get :step1, on: :collection
    patch :step2, on: :collection
    patch :step3, on: :collection
    patch :step4, on: :collection
  end


  resources :gardens do
    resources :garden_steps, only: [:create]
  end

  resources :garden_steps, only: [:show, :edit, :update]


  resources :gardens
  resources :steps, only: [:show]

  get "gardens/:id/packages", to: "gardens#packagechoice", as: "packagechoice"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord

  attr_accessor :current_step
  belongs_to :user
  has_many :garden_steps, dependent: :destroy
  has_one_attached :photo
end

def current_step
  @current_step ||= 1
end

def current_step=(step)
  @current_step = step.to_i
end

app/models/garden_step.rb
class GardenStep < ApplicationRecord
  belongs_to :step
  belongs_to :garden
  has_many :tasks, through: :step
  enum status: ["🌱 A faire !", "🎉 Etape terminée !"]
end

app/models/package.rb
class Package < ApplicationRecord
  has_many :steps
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :package
  has_many :tasks
  has_one_attached :photo
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :step
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gardens
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # app/controllers/application_controller.rb

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/garden_form_controller.rb
class GardenFormController < ApplicationController
  before_action :garden_create, only: [:step2, :step2, :step3, :step4, :update]
    def step1
      @garden = Garden.create!(user: current_user)
    end

    def step2
      @garden.update(name: garden_params[:name])
    end

    def step3
      @garden.update(size: garden_params[:size])
    end

    def step4
      @garden.update(exposition: garden_params[:exposition])
    end

  def update
    @garden.update(address: garden_params[:address])

    case @garden.size
    when "Jardinière"
      file = File.open(Rails.root.join("app/assets/images/garden_size/size_1_jardiniere.webp"))
      @garden.photo.attach(io: file, filename: "size_1_jardiniere.webp", content_type: "image/webp")
    when "Bac potager"
      file = File.open(Rails.root.join("app/assets/images/garden_size/size_2_bac.jpeg"))
      @garden.photo.attach(io: file, filename: "size_2_bac.jpeg", content_type: "image/jpeg")
    when "Potager"
      file = File.open(Rails.root.join("app/assets/images/garden_size/size_3_potager.webp"))
      @garden.photo.attach(io: file, filename: "size_3_potager.webp", content_type: "image/webp")
    end

    if @garden
      redirect_to packagechoice_path(@garden)
    else
      render :step1, notice: "Le jardin a flêtri"
    end
  end

  private

  def garden_create
    @garden = current_user.gardens.last
  end

  def garden_params
    params.require(:garden).permit(:name, :size, :exposition, :address)
  end
end

app/controllers/garden_steps_controller.rb
class GardenStepsController < ApplicationController
  before_action :set_garden_step, only: [:show, :update]

  def show
    @step = @garden_step.step
    @tasks = @step.tasks
    @garden = @garden_step.garden
  end

  def update
    set_garden_step
    @garden_step.update(status: garden_step_params[:status].to_i)
    redirect_to garden_path(@garden_step.garden)
  end

  def create
    garden = Garden.find(params[:garden_id])
    package = Package.find(params[:package_id])
    steps = Step.where(package: package)
      steps.each do |step|
        GardenStep.create!(garden: garden, step: step)
      end
    redirect_to garden_path(garden)
  end

  private

  def set_garden_step
    @garden_step = GardenStep.find(params[:id])
  end

  def garden_step_params
    params.require(:garden_step).permit(:status)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:edit, :next_step, :previous_step]
# :update dans only si retour a la normal

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user
    @garden.save
    redirect_to packagechoice_path(@garden)
  end

  def index
    @mygardens = Garden.all.where(user: current_user)
  end

  def show
    @garden = Garden.find(params[:id])
    @garden_steps = @garden.garden_steps.includes(:step).sort_by { |garden_step| garden_step.step.order }
  end

  def destroy
    @garden = Garden.find(params[:id])
    @garden.destroy
    # No need for app/views/gardens/destroy.html.erb
    redirect_to gardens_path, status: :see_other
  end

  def packagechoice
    @garden = Garden.find(params[:id])
    @packages = Package.where(size: @garden.size)
  end

  def new
    @garden = Garden.new
    @garden.current_step = 1
    render :step1
  end

  def edit
    case @garden.current_step
    when 1
      render :step1
    when 2
      render :step2
    when 3
      render :step3
    when 4
      render :step4
    else
      redirect_to @garden
    end
  end

  def next_step
    @garden.assign_attributes(garden_params)
    if params[:next]
      @garden.current_step += 1 if @garden.valid?
    elsif params[:back]
      @garden.current_step -= 1 if @garden.current_step > 1
    end

    @garden.save(validate: false)

    case @garden.current_step
    when 1
      render :step1
    when 2
      render :step2
    when 3
      render :step3
    when 4
      render :step4
    else
      redirect_to @garden
    end
  end

  def previous_step
    @garden.current_step -= 1 if @garden.current_step > 1
    @garden.save(validate: false)

    case @garden.current_step
    when 1
      render :step1
    when 2
      render :step2
    when 3
      render :step3
    when 4
      render :step4
    else
      redirect_to @garden
    end
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:name, :size, :exposition, :address, :photo)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/garden_form/step1.html.erb
<% content_for :meta_title, "#{"Etape 1"} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Donnez un petit nom à votre potager" %>

<div class="create-step-body">
  <div class="formular-title">
    <h2>Donnez un petit nom à votre potager</h2>
  </div>
  <div class="formulaire-du-potager">
    <%= form_for @garden, data: {turbo: false}, url: step2_garden_form_index_path do |f| %>
      <%= f.text_field :name, class: 'field-name', placeholder: "nom du potager ..." %>
    <% end %>
  </div>
  <p class="description-name">Pensez à un nom sympa comme <strong>Mon pote à moi</strong> ou <strong>Boustiflor</strong></p>
  <%= image_tag "garden_create/step_1_name.png", class: "image-photo-step1" %>

  <div class="create-step-foot-container">
    <%= link_to gardens_path do %>
      <div class="btnback">
      <i class="fa-solid fa-arrow-left-long"></i>
      </div>
    <% end %>
    <%= button_tag :submit, form: "edit_garden_#{@garden.id}", class: "btnback", data: {turbo_method: :patch} do %>
      <i class="fa-solid fa-check"></i>
    <% end %>
  </div>
</div>

app/views/garden_form/step2.html.erb
<% content_for :meta_title, "#{"Etape 2"} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Quelle va être la taille de votre petit coin de paradis ?" %>

<div class="create-step-body">
  <div class="formular-title">
    <h2>Quelle va être la taille de votre petit coin de paradis ?</h2>
  </div>
  <div class="formulaire-du-potager">
    <%= form_for @garden, data: {turbo: false}, url: step3_garden_form_index_path do |f| %>
      <div class="radio-buttons">
        <div class="content-radio-button">
          <%= f.radio_button :size, 'Jardinière', id: 'size_jardiniere', class: "radio-button-to-shrink" %>
          <%= f.label :size, 'Jardinière', for: 'size_jardiniere' %>
        </div>

        <div class="content-radio-button", for='size_bac_potager'>
          <%= f.radio_button :size, 'Bac potager', id: 'size_bac_potager', class: "radio-button-to-shrink" %>
          <%= f.label :size, 'Bac potager', for: 'size_bac_potager' %>
        </div>

        <div class="content-radio-button">
          <%= f.radio_button :size, 'Potager partagé', id: 'size_potager_partage', class: "radio-button-to-shrink" %>
          <%= f.label :size, 'Potager partagé', for: 'size_potager_partage'  %>
        </div>

      </div>
    <% end %>
  </div>
  <p class="description-name">Nous avons besoin de la taille de votre futur potager afin d’optimiser au mieux les plantes choisies.</p>
  <%= image_tag "garden_create/step_2_size.png", class: "image-photo-step2" %>

  <div class="create-step-foot-container">
    <%= link_to step1_garden_form_index_path do %>
      <div class="btnback">
        <i class="fa-solid fa-arrow-left-long"></i>
      </div>
    <% end %>

    <%= button_tag :submit, form: "edit_garden_#{@garden.id}", class: "btnback", data: {turbo_method: :patch} do %>
      <i class="fa-solid fa-check"></i>
    <% end %>
  </div>
</div>

app/views/garden_form/step3.html.erb
<% content_for :meta_title, "#{"Etape 3"} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "A quel moment de la journée avez vous du soleil ?" %>

<div class="create-step-body">
  <div class="formular-title">
    <h2>A quel moment de la journée avez vous du soleil ?</h2>
  </div>
  <div class="formulaire-du-potager">
    <%= form_for @garden, data: {turbo: false}, url: step4_garden_form_index_path do |f| %>
      <%#= f.label :Exposition %>
      <%#= f.select :exposition, ['Pas de soleil', 'Soleil le matin', 'Soleil le midi', 'Soleil en après midi'] %>
      <div class="radio-buttons">
        <div class="content-radio-button">
          <%= f.radio_button :exposition, 'Pas de soleil', id: 'expo_no_sun', class: "radio-button-to-shrink"  %>
          <%= f.label :exposition, 'Pas de soleil', for: 'expo_no_sun' %>
        </div>
        <div class="content-radio-button">
          <%= f.radio_button :exposition, 'Soleil le matin', id: 'expo_morning_sun', class: "radio-button-to-shrink"  %>
          <%= f.label :exposition, 'Soleil le matin', for: 'expo_morning_sun' %>
        </div>
        <div class="content-radio-button">
          <%= f.radio_button :exposition, 'Soleil le midi', id: 'expo_noon_sun', class: "radio-button-to-shrink"  %>
          <%= f.label :exposition, 'Soleil le midi', for: 'expo_noon_sun' %>
        </div>
        <div class="content-radio-button">
          <%= f.radio_button :exposition, 'Soleil en après midi', id: 'expo_afternoon_sun', class: "radio-button-to-shrink"  %>
          <%= f.label :exposition, 'Soleil en après midi', for: 'expo_afternoon_sun' %>
        </div>
      </div>
    <% end %>
  </div>
  <p class="description-name">A quel moment de la journée avez vous du soleil ?</p>
  <%= image_tag "garden_create/step_3_exposition.png", class: "image-photo-step3" %>

  <div class="create-step-foot-container">
    <%= link_to :back do %>
      <div class="btnback">
      <i class="fa-solid fa-arrow-left-long"></i>
      </div>
    <% end %>
    <%#= link_to step2_garden_form_index_path do %>
      <%= button_tag :submit, form: "edit_garden_#{@garden.id}", class: "btnback", data: {turbo_method: :patch} do %>
        <i class="fa-solid fa-check"></i>
      <% end %>
    <%# end %>
  </div>
</div>

app/views/garden_form/step4.html.erb
<% content_for :meta_title, "#{"Etape 4"} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Où se trouve votre potager ?" %>

<div class="create-step-body">
  <div class="formular-title">
    <h2>Où se trouve votre potager ?</h2>
  </div>
  <div class="formulaire-du-potager">
    <%= form_for @garden, data: {turbo: false}, url: garden_form_path(@garden) do |f| %>
      <%= f.text_field :address, class: 'field-name', placeholder: 'adresse ...' %>
    <% end %>
  </div>
  <p class="description-name">Si nous vous demandons votre localisation, c’est pour pouvoir estimer au mieux le climat de votre tout nouveau potager. </p>
  <%= image_tag "garden_create/step_4_address.png", class: "image-photo-step4" %>

  <div class="create-step-foot-container">
    <%= link_to step3_garden_form_index_path do %>
      <div class="btnback">
        <i class="fa-solid fa-arrow-left-long"></i>
      </div>
    <% end %>

    <%= button_tag :submit, form: "edit_garden_#{@garden.id}", class: "btnback", data: {turbo_method: :patch} do %>
      <i class="fa-solid fa-check"></i>
    <% end %>
  </div>
</div>

app/views/garden_steps/show.html.erb
<% content_for :meta_title, "#{@step.name} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @step.description %>

<div class="garden-steps-main-container">
  <div class="garden_steps_banner">
    <h1><%= @step.name %></h1>
  </div>

  <div class="container-show">

    <div class="data-controller" data-controller="tabs" data-tabs-active-class="active" data-tabs-default-tab-value="tab1">

    <div class="nav-nav-tabs">
      <button class="nav-link" id="tab1" data-tabs-target="btn" data-action="click->tabs#select"><h4>1</h4></button>
      <button class="nav-link" id="tab2" data-tabs-target="btn" data-action="click->tabs#select"><h4>2</h4></button>
      <button class="nav-link" id="tab3" data-tabs-target="btn" data-action="click->tabs#select"><h4>3</h4></button>
    </div>

    <div class="rounded-lg categories">
      <div data-tabs-target="tab" id="tab1" class="infos">
        <% @tasks.order(1)%>
        <div class= "infos-tech">
          <h2 class="pictogram"><i class="fa-solid fa-shop fa-2xl" style="color: #0b4f30;"></i></h2>
          <h3><%= @tasks[0].name %></h3>
          <h2 class="pictogram"><i class="fa-solid fa-trowel fa-2xl" style="color: #0b4e31;"></i></h2>
          <p><%= @tasks[0].description.html_safe %></p>
            <% if @tasks[0].name == "Aller chercher du terreau"%>
              <a href="https://www.lovethegarden.com/fr-fr/calculateur/terreau" target="_blank" class="btn-green-filled">Calcul terreau</a>
              <% else %>
            <% end %>
        </div>
      </div>

      <div data-tabs-target="tab" id="tab2" class='hidden'>
        <p><% @tasks.order(2)%></p>
            <div class= "infos-tech">
              <h2 class="pictogram"><i class="fa-solid fa-leaf fa-2xl"></i></h2>
              <h3><%= @tasks[1].name %></h3>
              <h2 class="pictogram"><i class="fa-solid fa-seedling fa-2xl"></i></h2>
              <p><%= @tasks[1].description  %></p>
            </div>
      </div>

        <div data-tabs-target="tab" id="tab3" class='hidden'>
          <p><% @tasks.order(3)%></p>
            <div class= "infos-tech">
              <h2 class="pictogram"><i class="fa-solid fa-worm fa-2xl"></i></h2>
              <h3><%= @tasks[2].name %></h3>
              <h2 class="pictogram"><i class="fa-solid fa-trowel fa-2xl" style="color: #0b4e31;"></i></h2>
              <p><%=@tasks[2].description %></p>
            </div>
        </div>
      </div>
    </div>
    <div class= "filler-div">
      <%# Div vide necessaire/ ne pas effacer %>
    </div>
  </div>

    <div class="bottom-buttons-container">

      <%= link_to garden_path(@garden_step.garden) do %>
        <div class="btnback">
          <i class="fa-solid fa-arrow-left-long"></i>
        </div>
      <% end %>

      <%= simple_form_for(@garden_step) do |f| %>
        <div class="d-none">
          <%= f.input :status, input_html: {value: 0}%>
        </div>
        <%= button_tag(type: 'submit', class: "btnback") do %>
          <i class="fa-regular fa-hourglass-half"></i>
        <% end %>
      <% end %>

      <%= simple_form_for(@garden_step) do |f| %>
        <div class="d-none">
          <%= f.input :status, input_html: {value: 1}%>
        </div>
          <%= button_tag(type: 'submit', class: "btnback") do %>
            <i class="fa-solid fa-check"></i>
          <% end %>
      <% end %>
    </div>
 </div>

app/views/gardens/index.html.erb
<% content_for :meta_title, "#{"Mes potagers !"} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Voici la liste de tous vos potagers" %>

<div class="garden-index-main-container">
  <% if @mygardens.empty? %>
    <div class="no-gardens-message">
      <div class="garden-index-title-container">
          <h1>Mes potagers</h1>
      </div>
      <div><%= image_tag "garden_pictures/bac_à_potager.png", alt: "Illustration", class: "no-gardens-picture" %></div>
      <div><p>Créez votre nouveau potager!</p></div>
      <div class="no-gardens-arrow-container">
        <%= image_tag "arrow.png", alt: "Fleche vers le bas" %>
        </div>
    </div>
  <% else %>
  <div class="garden-index-title-container">
    <h1>Mes potagers</h1>
  </div>
    <div class="gardens-index-cards-container">
      <% @mygardens.each do |garden| %>
        <%= link_to garden_path(garden), class: "garden-card-link" do %>
          <div class="garden-card">
            <div class="garden-index-picture-container">
              <% if garden.size == "Jardinière" %>
                <%= image_tag "garden_size/size_1_jardiniere.webp", alt: "Image d'une jardinière", class: "garden-index-picture" %>
              <% elsif garden.size == "Bac potager" %>
                <%= image_tag "garden_size/size_2_bac.jpeg", alt: "Image d'un bac potager", class: "garden-index-picture" %>
              <% else garden.size == "potager partagé" %>
                <%= image_tag "garden_size/size_3_potager.webp", alt: "Image d'un potager", class: "garden-index-picture" %>
              <% end %>
            </div>
            <div class="garden-index-info">
              <h2><%= garden.name %></h2>
              <div class="garden-index-info-bottom-line">
                <p> <%= garden.size %> </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
    <%= link_to step1_garden_form_index_path do %>
    <i class="fa-solid fa-circle-plus new-garden-button"></i>
  <% end %>
</div>

app/views/gardens/new.html.erb
<%# <h1 class = "titre-form">Créer un nouveau potager</h1>
<div class= 'formulaire-du-potager'> %>
<%= form_with(model: [@garden], url: gardens_path, method: :post) do |form| %>
  <%= form.hidden_field :current_step, value: @current_step %>
  <div data-controller="step-one">
    <label>
      Name:
      <%= form.text_field :name %>
    </label>
    <button type="submit" data-action="submit">Next</button>
  </div>
<% end %>

app/views/gardens/packagechoice.html.erb
<% content_for :meta_title, "#{"Choix du kit potager"} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Sélectionnez le kit qui vous convient" %>

<div class="package-choice-container">
  <div class="picto-haut">
    <%= image_tag("garden_pictures/planter.png") %>
  </div>
    <h2>Choix du kit potager</h2>
      <div class="h3_shadow">
        <h3>Pour <strong><%=@garden.name%></strong>, sélectionnez le kit qui vous convient : </h3>
      </div>
        <div class="scroll-content">
          <div class="scroll-container">
            <div class="package-choice-iteration-container">
              <%=form_with url: garden_garden_steps_path(@garden), method: "post" do |f| %>
                <% @packages.each do |package|  %>
                  <div class="item">
                    <%= f.radio_button 'package_id', package.id, class: "package-choice-radio-button" %>
                    <%= f.label "package_id_#{package.id}" do %>
                      <div class= "package-choice-iteration-card">
                        <%= image_tag("categories/#{package.category.downcase}.jpg")  %>
                        <div class= "package-choice-iteration-card-infos">
                          <h2><%= package.category %></h2>
                          <h3><%= package.name %></h3>
                          <p><%= package.description %></p>
                        </div>
                      </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
</div>

<div class="package-choice-bottom-buttons-container">
  <%= link_to new_garden_path do %>
    <div class="btnback">
      <i class="fa-solid fa-arrow-left-long"></i>
    </div>
  <% end %>
  <%= button_tag :submit, class:"btnback" do%>
    <i class="fa-solid fa-check"></i>
  <% end %>
<% end %>
 </div>

app/views/gardens/show.html.erb
<% content_for :meta_title, "#{@garden.name} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @garden.name %>

<div class="garden-show-main-container">

  <div class="garden-show-banner">
    
    <% if @garden.size == "Jardinière" %>
      <div class="background-image" style="background-image: url('<%= image_path("garden_size/size_1_jardiniere.webp") %>');"></div>
    <% elsif @garden.size == "Bac potager" %>
      <div class="background-image" style="background-image: url('<%= image_path("garden_size/size_2_bac.jpeg") %>');"></div>
    <% elsif @garden.size == "potager partagé" %>
      <div class="background-image" style="background-image: url('<%= image_path("garden_size/size_3_potager.webp") %>');"></div>
    <% end %>

    <div class="garden-name">
      <h2><%= @garden.name %></h2>
    </div>

    <div class="delete-button-card">
      <div class="delete-button">
        <%= link_to garden_path(@garden), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr?"} do %>
          <i class="fa-regular fa-trash-can" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>

  </div>

  <div class="step">
    <% @garden_steps.each do |garden_step| %>
      <%= link_to garden_step_path(garden_step) do %>
        <div class="step-card <%= 'step-card-completed' if garden_step.status == '🎉 Etape terminée !' %>">
          <div class="step-image">
            <%= cl_image_tag garden_step.step.photo.key, class: "img-card" %>
          </div>
          <div class="step-card-info">
            <h5>Étape <%= garden_step.step.order %></h5>
            <p><%= garden_step.step.name %></p>
            <div class="status">
              <strong><%= garden_step.status %></strong>
            </div>
          </div>
          <div class="step-arrow-container">
            <i class="fa-solid fa-chevron-right"></i>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="return-button-container-garden-show">
    <%= link_to gardens_path do %>
      <div class="btnback">
        <i class="fa-solid fa-arrow-left-long"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <title>Le petit Guide Vert</title> %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicon.ico'%>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!– Facebook Open Graph data –>
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!– Twitter Card data –>
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# PWA setup %>
    <%# Prepare app for A2HS %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%# Loadthe config manifest.json for PWA icons %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%# render the "_ios_pwa_links.html.erb" partial %>
    <%= render 'shared/ios_pwa_links' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body class="app-main-body">
        <%= render "shared/flashes" %>
    <% unless action_name == 'home' || ["registration","sessions"].include?(controller_name) %>
      <%= render "shared/navbar" %>
    <% end %>
    <div class="app-main-container">
        <%= yield %>
    </div>
  </body>
</html>